Remove excess spacing before multiline block
VincentLanglet/Twig-CS-Fixer pull request #247
Opened 2024-07-03 18:20 UTC by ruudk

Fixes #245

This is not working yet.

2024-07-03 20:59 UTC, VincentLanglet commented
If you want to take a look, I added a commit which seems to fix everything except
```
Error: Cannot unpack array with string keys
```
which is a PHP 8 specific error.

Some shared thought:
I'm not sure the AbstractSpacingRule should `implements ConfigurableRuleInterface` by default. We might prefer to enable the config manually on the different rules. This PR is adding `skipIfNewLine` option for the rules:
  - OperatorSpacingRule
  - DelimiterSpacingRule
  - BlockNameSpacingRule
  - PunctuationSpacingRule

Maybe it's better to just make the DelimiterSpacingRule configurable for now, and add
```
public function __construct() {
    parent::__construct();
}
```
to other rules in order to remove the param from them (so far) and wait for feature request (?) This way we could know
- if the option is required
- if the option should be the first param of the rule (as an example PunctuationSpacingRule already has option).

Does it seem ok to you ?

2024-07-04 06:55 UTC, ruudk commented
@VincentLanglet Thanks so much for helping me out! I agree with what you're saying. I just rebased the PR and made the suggested changes. Let me know what you think!

2024-07-04 07:01 UTC, VincentLanglet requested changes

2024-07-04 07:01 UTC, VincentLanglet commented on src/Rules/AbstractSpacingRule.php
> +    }
We can simplify to

```suggestion
    protected bool $skipIfNewLine = false;
```
And setting the value in the construct of DelimiterSpacingRule with the implementation of getConfiguration

2024-07-04 07:01 UTC, VincentLanglet commented on src/Rules/Punctuation/PunctuationSpacingRule.php
> +        return parent::getConfiguration() + [
```suggestion
        return [
```

2024-07-04 07:01 UTC, VincentLanglet commented on src/Rules/Punctuation/PunctuationSpacingRule.php
> +        parent::__construct();
This won't be needed with the previous suggestion

2024-07-04 07:01 UTC, VincentLanglet commented on tests/Rules/Punctuation/PunctuationSpacing/PunctuationSpacingRuleTest.php
> +                'skipIfNewLine' => true,
Shouldn't be added to the config since it's unused

2024-07-04 07:10 UTC, ruudk commented
Applied the feedback!

2024-07-04 07:12 UTC, ruudk commented
Pushed an updated test that now fails.. I think it should also remove the spaces.

2024-07-04 07:40 UTC, VincentLanglet commented
I wont be able to debug this before the next week since I dont have a computer ATM.

2024-07-09 21:09 UTC, VincentLanglet commented
> Pushed an updated test that now fails.. I think it should also remove the spaces.

Hi @ruudk, I don't have any real failure with
```
{%

    trans with {
    contactUrl: 'http://contact',
}

    %}my.key{% endtrans %}
````
I just need to update tests/failure message.

But I think the failed test you wanted is the one with only one space
```
{%

    trans with {
    contactUrl: 'http://contact',
}

 %}my.key{% endtrans %}
```

Is it the issue you encounter ? If yes, I'll take a look.

2024-07-10 06:36 UTC, ruudk commented
Yes, I couldn't provide a good failing test.

So I think what we want is that with `skipIfNewLine=true` (default) the following will be changed:
```diff
 {%
 
     trans with {
     contactUrl: 'http://contact',
 }
 
-    %}my.key{% endtrans %}
+ %}my.key{% endtrans %}
```
So it changes 4 spaces after to 1 space after.

And then with `skipIfNewLine=false` it should do the following:
```diff
 {%
 
     trans with {
     contactUrl: 'http://contact',
- }
- 
-    %}my.key{% endtrans %}
+ } %}my.key{% endtrans %}
```

It should take the 4 spaces + the 2 newlines, and convert that to 1 space.

2024-07-10 06:38 UTC, ruudk commented
I think `\TwigCsFixer\Tests\Rules\AbstractRuleTestCase::checkRule` can be improved.

It should not immediately fail the test when one of the diffs fails. It should print the diff, then continue with showing the diff for the violations, and at the end fail it. This way, when you are trying to create a failing test, you can see the violations too. Now, I had to comment that part out, in order to see what the violations would be.

2024-07-10 06:45 UTC, VincentLanglet commented
> So I think what we want is that with `skipIfNewLine=true` (default) the following will be changed:
> 
> ```diff
>  {%
>  
>      trans with {
>      contactUrl: 'http://contact',
>  }
>  
> -    %}my.key{% endtrans %}
> + %}my.key{% endtrans %}
> ```

Not really, with skipIfNewLine let untouched this code because there is a new line before the last non empty token and `%}`. This allow to
- Add a new line
- Indent your code after the new line

> And then with `skipIfNewLine=false` it should do the following:
> 
> ```diff
>  {%
>  
>      trans with {
>      contactUrl: 'http://contact',
> - }
> - 
> -    %}my.key{% endtrans %}
> + } %}my.key{% endtrans %}
> ```
> 
> It should take the 4 spaces + the 2 newlines, and convert that to 1 space.

It's understandable. That also mean that if you have only one space, new lines will be removed

```diff
 {%
 
     trans with {
     contactUrl: 'http://contact',
- }
- 
-  %}my.key{% endtrans %}
+ } %}my.key{% endtrans %}
```

2024-07-10 07:02 UTC, ruudk commented
> It's understandable. That also mean that if you have only one space, new lines will be removed

I think this is what I want with this feature. See newlines also as whitespace and enforce it regardless.

I never write 

```twig
{%
  if var == true 
%}
```

or

```twig
{% 
trans into 'nl'
%}my.key{%endtrans %}
```

Am I missing something? Is this common? 

Also, this rule is not default enabled, so we can make this different?

2024-07-10 07:04 UTC, VincentLanglet commented
It should be ok with the latest commit https://github.com/VincentLanglet/Twig-CS-Fixer/pull/247/commits/33fb7bb2922a61a36310ad7e28592a20409c3e6d @ruudk

2024-07-10 07:29 UTC, ruudk commented
@VincentLanglet Amazing 🎉 Thank you!

2024-07-10 08:43 UTC, VincentLanglet approved these changes

2024-07-10 08:44 UTC, merged

2024-07-10 08:44 UTC, VincentLanglet commented
Thanks